/**
 * API whatsgate.ru
 * Интерфейс для взаимодействия с клиентом Whatsapp
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param whatsappID Идентификатор Whatsapp ID
 * @param number Номер в формате 79999999999
 */
data class CheckBody (

    /* Идентификатор Whatsapp ID */
    val whatsappID: kotlin.String? = null,
    /* Номер в формате 79999999999 */
    val number: kotlin.String? = null
) {
}