/**
 * API whatsgate.ru
 * Интерфейс для взаимодействия с клиентом Whatsapp
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param body 
 * @param quote 
 * @param type 
 */
data class MessageText (

    val body: kotlin.String,
    val quote: kotlin.String? = null,
    val type: MessageText.Type? = null
) {
    /**
    * 
    * Values: TEXT
    */
    enum class Type(val value: kotlin.String){
        TEXT("text");
    }
}