/**
 * API whatsgate.ru
 * Интерфейс для взаимодействия с клиентом Whatsapp
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.Media

/**
 * 
 * @param body 
 * @param quote 
 * @param type 
 * @param media 
 */
data class MessageMedia (

    val body: kotlin.String? = null,
    val quote: kotlin.String? = null,
    val type: MessageMedia.Type? = null,
    val media: Media? = null
) {
    /**
    * 
    * Values: IMAGE,STICKER,DOC,VOICE
    */
    enum class Type(val value: kotlin.String){
        IMAGE("image"),
        STICKER("sticker"),
        DOC("doc"),
        VOICE("voice");
    }
}