/**
 * API whatsgate.ru
 * Интерфейс для взаимодействия с клиентом Whatsapp
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param number Recipient number
 * @param type Recipient type, group or contact
 */
data class RecipientNum (

    /* Recipient number */
    val number: kotlin.String,
    /* Recipient type, group or contact */
    val type: RecipientNum.Type? = null
) {
    /**
    * Recipient type, group or contact
    * Values: GROUP,CONTACT
    */
    enum class Type(val value: kotlin.String){
        GROUP("group"),
        CONTACT("contact");
    }
}