/**
 * API whatsgate.ru
 * Интерфейс для взаимодействия с клиентом Whatsapp
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.ResponseChatGroupMetadata

/**
 * 
 * @param id Идентификатор контакта или группы в формате WhatsApp
 * @param name Имя контакта или группы
 * @param isGroup Является ли чат контактом или группой
 * @param isReadOnly Является ли чат ReadOnly
 * @param unreadCount Количество непрочитанных сообщений в чате
 * @param timestamp Время последней активночти в чате
 * @param pinned Является ли чат закрепленным
 * @param isMuted Выключен ли у чата звук
 * @param muteExpiration Время, оставшееся до включения звука
 * @param groupMetadata 
 */
data class ResponseChat (

    /* Идентификатор контакта или группы в формате WhatsApp */
    val id: kotlin.String? = null,
    /* Имя контакта или группы */
    val name: kotlin.String? = null,
    /* Является ли чат контактом или группой */
    val isGroup: kotlin.Boolean? = null,
    /* Является ли чат ReadOnly */
    val isReadOnly: kotlin.Boolean? = null,
    /* Количество непрочитанных сообщений в чате */
    val unreadCount: kotlin.Int? = null,
    /* Время последней активночти в чате */
    val timestamp: kotlin.Int? = null,
    /* Является ли чат закрепленным */
    val pinned: kotlin.Boolean? = null,
    /* Выключен ли у чата звук */
    val isMuted: kotlin.Boolean? = null,
    /* Время, оставшееся до включения звука */
    val muteExpiration: kotlin.Boolean? = null,
    val groupMetadata: ResponseChatGroupMetadata? = null
) {
}