/**
 * API whatsgate.ru
 * Интерфейс для взаимодействия с клиентом Whatsapp
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param id Идентификатор контакта в формате WhatsApp
 * @param isAdmin Является ли участник администратором
 * @param isSuperAdmin Является ли участник суперадминистратором
 */
data class ResponseChatGroupMetadataParticipants (

    /* Идентификатор контакта в формате WhatsApp */
    val id: kotlin.String? = null,
    /* Является ли участник администратором */
    val isAdmin: kotlin.Boolean? = null,
    /* Является ли участник суперадминистратором */
    val isSuperAdmin: kotlin.Boolean? = null
) {
}