/**
 * API whatsgate.ru
 * Интерфейс для взаимодействия с клиентом Whatsapp
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.ResponseChatGroupMetadataParticipants

/**
 * Метаданные группы, если чат является группой
 * @param id Идентификатор группы в формате WhatsApp
 * @param creation Дата создания группы в формате Unix Time Stamp
 * @param owner Идентификатор создателя группы в формате WhatsApp
 * @param size Количество участников в группе
 * @param participants Массив участников
 */
data class ResponseChatGroupMetadata (

    /* Идентификатор группы в формате WhatsApp */
    val id: kotlin.String? = null,
    /* Дата создания группы в формате Unix Time Stamp */
    val creation: kotlin.Int? = null,
    /* Идентификатор создателя группы в формате WhatsApp */
    val owner: kotlin.String? = null,
    /* Количество участников в группе */
    val size: kotlin.Int? = null,
    /* Массив участников */
    val participants: kotlin.Array<ResponseChatGroupMetadataParticipants>? = null
) {
}