/**
 * API whatsgate.ru
 * Интерфейс для взаимодействия с клиентом Whatsapp
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param id Идентификатор сообщения
 * @param ack Флаг просмотра сообщения
 * @param hasMedia Флаг, имеет ли сообщение медиафайл
 * @param mediaKey Ключ медиафайла (при наличии)
 * @param body Текст сообщения
 * @param type Тип сообщения
 * @param timestamp Время сообщения в формате Unix Timestamp
 * @param from Идентификатор отправителя в формате WhatsApp
 * @param to Идентификатор получателя в формате WhatsApp
 * @param isForwarded Флаг, было ли сообщение перенаправлено
 */
data class ResponseMessage (

    /* Идентификатор сообщения */
    val id: kotlin.String? = null,
    /* Флаг просмотра сообщения */
    val ack: kotlin.Int? = null,
    /* Флаг, имеет ли сообщение медиафайл */
    val hasMedia: kotlin.Boolean? = null,
    /* Ключ медиафайла (при наличии) */
    val mediaKey: kotlin.String? = null,
    /* Текст сообщения */
    val body: kotlin.String? = null,
    /* Тип сообщения */
    val type: kotlin.String? = null,
    /* Время сообщения в формате Unix Timestamp */
    val timestamp: kotlin.Int? = null,
    /* Идентификатор отправителя в формате WhatsApp */
    val from: kotlin.String? = null,
    /* Идентификатор получателя в формате WhatsApp */
    val to: kotlin.String? = null,
    /* Флаг, было ли сообщение перенаправлено */
    val isForwarded: kotlin.Boolean? = null
) {
}