/**
 * API whatsgate.ru
 * Интерфейс для взаимодействия с клиентом Whatsapp
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param whatsappID Service Whatsapp ID
 * @param async Async query returns Message Object
 * @param recipient 
 * @param message 
 */
data class SendBody (

    /* Service Whatsapp ID */
    val whatsappID: kotlin.String,
    /* Async query returns Message Object */
    val async: kotlin.Boolean? = null,
    val recipient: AnyOfsendBodyRecipient? = null,
    val message: AnyOfsendBodyMessage? = null
) {
}